server:
  port: 8001
spring:
  datasource:
    url: ${POSTGRES_DATABASE_URL:jdbc:postgresql://localhost:5432/customers}
    username: ${POSTGRES_DATABASE_USERNAME:postgres}
    password: ${POSTGRES_DATABASE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true